const scenarios={
 corporate:{name:"Corporate - diligence issue extraction",summary:"Surface agreement issues across a deal-room corpus for attorney verification and drafting decisions.",fact:"A transaction team needs faster issue spotting across contracts without surrendering relevance, materiality, or negotiating judgment.",record:"Approved matter corpus, clause taxonomy, document lineage, access controls, and a named knowledge owner.",authority:"Deal attorneys determine legal relevance, materiality, escalation, and the final drafting or negotiating position.",evaluation:"Attorney-reviewed issue set; citation completeness; omission and hallucination review; repeatability across representative documents.",adoption:"Matter kickoff pattern, embedded examples, office hours, feedback capture, and practice KM ownership.",value:"Measured cycle time, rework, issue coverage, repeat use, and client-response speed.",treatments:{prototype:["Matter prototype","Bounded pilot with attorney review on every output."],practice:["Practice pattern","Prove across representative matters and document the legitimate exceptions."],candidate:["Cross-practice candidate","Test the reusable components against another practice's fact pattern before standardizing."],standard:["Firm standard","Maintain evaluation, knowledge ownership, exception rules, and retirement criteria."]}},
 litigation:{name:"Litigation - discovery synthesis",summary:"Build chronology and theme support from a large review set while preserving privilege and strategy authority.",fact:"A litigation team needs a defensible synthesis of documents, chronology, actors, and emerging themes under time pressure.",record:"Matter-authorized collection, privilege boundaries, review coding, document citations, and chain-of-custody context.",authority:"Litigators decide responsiveness, privilege, factual significance, theory of the case, and what reaches the client or court.",evaluation:"Citation validity; factual consistency; privilege leakage tests; theme coverage; reviewer agreement on sampled outputs.",adoption:"Reviewer playbook, escalation path, matter-specific training, and continuous feedback from senior litigators.",value:"Measured review effort, chronology build time, rework, factual coverage, and team confidence.",treatments:{prototype:["Matter prototype","Use only inside a bounded review lane with heightened supervision."],practice:["Practice pattern","Separate reusable synthesis mechanics from matter-specific privilege and strategy rules."],candidate:["Cross-practice candidate","Reuse citation and chronology controls; do not export matter strategy assumptions."],standard:["Firm standard","Standardize the control pattern, not the legal judgment."]}},
 regulatory:{name:"Regulatory - monitoring to advisory update",summary:"Turn changing regulatory sources into a traceable attorney-ready update with accountable interpretation.",fact:"A regulatory team must detect change, understand client relevance, and produce timely advice across fast-moving sources.",record:"Approved primary sources, jurisdiction taxonomy, effective dates, client context, and source-refresh ownership.",authority:"Regulatory lawyers interpret applicability, uncertainty, materiality, and the advice delivered to clients.",evaluation:"Source freshness; citation coverage; change-detection recall; jurisdiction accuracy; attorney correction patterns.",adoption:"Practice alerts, client-context prompts, review checkpoints, and shared KM stewardship.",value:"Measured monitoring effort, time to attorney-ready draft, corrections, coverage, and client-response speed.",treatments:{prototype:["Matter prototype","Test source coverage and change detection before drafting assistance."],practice:["Practice pattern","Define jurisdiction limits, source ownership, and attorney review rules."],candidate:["Cross-practice candidate","Reuse monitoring mechanics where source taxonomies and authority rules align."],standard:["Firm standard","Maintain the source registry and revalidate when law, policy, or models change."]}},
 whitecollar:{name:"White Collar - investigation chronology support",summary:"Organize evidence and chronology for sensitive investigations with heightened confidentiality and human control.",fact:"An investigation team needs to connect communications, events, actors, and allegations without compromising privilege or investigative strategy.",record:"Matter-specific access, approved evidence set, privilege and export-control boundaries, provenance, and investigation taxonomy.",authority:"Investigation counsel decides scope, credibility, privilege, legal characterization, escalation, and disclosure.",evaluation:"Evidence citation accuracy; entity and date consistency; privilege controls; access tests; omission review on high-consequence facts.",adoption:"Small authorized cohort, scenario-based training, named escalation owner, and deliberate expansion only after evidence.",value:"Measured chronology effort, correction burden, issue coverage, response speed, and defensibility signals.",treatments:{prototype:["Matter prototype","Heightened controls; narrow access; no autonomous consequential action."],practice:["Practice pattern","Capture the technical pattern while keeping matter-specific access and strategy local."],candidate:["Cross-practice candidate","Transfer provenance and chronology controls, not investigative assumptions."],standard:["Firm standard","Standardize only the controls that remain defensible across sensitive matters."]}}
};
let current='corporate',stage='practice';
function render(animate=true){const s=scenarios[current],t=s.treatments[stage];
 const map={scenarioTitle:s.name,scenarioSummary:s.summary,fact:s.fact,record:s.record,authority:s.authority,evaluation:s.evaluation,adoption:s.adoption,value:s.value,heroDisposition:t[0],labDisposition:t[0],nextDecision:t[1],heroFact:s.fact,heroRecord:s.record,heroAuthority:s.authority,heroEvaluation:s.evaluation};
 Object.entries(map).forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=v});
 document.querySelectorAll('.scenario-btn').forEach(b=>b.setAttribute('aria-selected',b.dataset.scenario===current));
 document.querySelectorAll('.stage-btn').forEach(b=>b.setAttribute('aria-pressed',b.dataset.stage===stage));
 const notes=[...document.querySelectorAll('.headnote')]; notes.forEach(n=>n.classList.remove('visible'));
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!animate||reduced){notes.forEach(n=>n.classList.add('visible'))}else{notes.forEach((n,i)=>setTimeout(()=>n.classList.add('visible'),100+i*120))}
}
document.querySelectorAll('.scenario-btn').forEach(b=>b.addEventListener('click',()=>{current=b.dataset.scenario;render()}));
document.querySelectorAll('.stage-btn').forEach(b=>b.addEventListener('click',()=>{stage=b.dataset.stage;render()}));
document.getElementById('menuBtn')?.addEventListener('click',()=>{const nav=document.querySelector('.nav');const open=nav.classList.toggle('open');document.getElementById('menuBtn').setAttribute('aria-expanded',open)});
render(true);
